"""Public API for the 3loop asynchronous multi-agent framework."""

from .agents import CriticAgent, HeuristicAgent, RoleAgent, WriterAgent, parse_vote
from .backend import (
    AirLLMBackend,
    CloudApiBackend,
    DemoBackend,
    FunctionBackend,
    LlamaCppBackend,
    LiteLLMBackend,
    OllamaBackend,
    SharedLLMBackend,
)
from .models import (
    AGENT_ROLES,
    AgentRole,
    AgentTurn,
    ConsensusResult,
    CycleResult,
    EventType,
    PipelineEvent,
    RunResult,
    SearchResult,
    SourceMatch,
    TaskKind,
    TemperatureObservation,
    Vote,
    WebResearchResult,
)
from .pipeline import PipelineConfig, ThreeLoop, ThreeLoopPipeline
from .latent import LatentDebateCoordinator, parse_latent_debate
from .temperature import BetaPrior, TemperatureOptimizer
from .validation import (
    infer_task_kind,
    validate_format,
    validate_python,
    validate_solution,
)
from .web import (
    DuckDuckGoSearchProvider,
    SearchProvider,
    StaticSearchProvider,
    canonicalize_url,
    domain_from_url,
    intersect_sources,
    triangulate_sources,
    triangulate_web_sources,
)

__all__ = [
    "AGENT_ROLES",
    "AgentRole",
    "AgentTurn",
    "AirLLMBackend",
    "BetaPrior",
    "CloudApiBackend",
    "ConsensusResult",
    "CriticAgent",
    "CycleResult",
    "DemoBackend",
    "DuckDuckGoSearchProvider",
    "EventType",
    "FunctionBackend",
    "HeuristicAgent",
    "LlamaCppBackend",
    "LiteLLMBackend",
    "LatentDebateCoordinator",
    "OllamaBackend",
    "PipelineConfig",
    "PipelineEvent",
    "RoleAgent",
    "RunResult",
    "SearchProvider",
    "SearchResult",
    "SharedLLMBackend",
    "SourceMatch",
    "StaticSearchProvider",
    "TaskKind",
    "TemperatureObservation",
    "TemperatureOptimizer",
    "ThreeLoop",
    "ThreeLoopPipeline",
    "Vote",
    "WebResearchResult",
    "WriterAgent",
    "canonicalize_url",
    "domain_from_url",
    "infer_task_kind",
    "intersect_sources",
    "parse_vote",
    "parse_latent_debate",
    "triangulate_sources",
    "triangulate_web_sources",
    "validate_format",
    "validate_python",
    "validate_solution",
]
